name: Coleta Horária de Dados de Startups

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-data-collection:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Baixa o seu código para a máquina virtual
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python
      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Instala as dependências a partir do seu arquivo requirements.txt
      - name: Instalar bibliotecas
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. PASSO CRÍTICO: Cria o arquivo credentials.json a partir do Secret
      - name: Criar arquivo credentials.json
        run: echo "${{ secrets.GDRIVE_API_CREDENTIALS_JSON }}" > credentials.json
        shell: bash

      # 5. PASSO DE DIAGNÓSTICO: Lista os arquivos para verificar se o passo anterior funcionou
      - name: Verificar se o credentials.json foi criado
        run: ls -l

      # 6. Executa o seu script principal
      - name: Executar script de coleta (main.py)
        run: python main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
